spring:
  application:
    name: stockflow-api

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  servlet:
    context-path: /api/v1

springdoc:
  api-docs:
    path: /v3/api-docs

  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO

jwt:
  secret: 1234567890123456789012345678901234567890123456789012345678901234
  expiration: 86400000

